[package]
name = "oxidize-core"
version = "0.1.0"
authors = ["Steve Toth <steve@toths.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name = "echo"
path = "src/echo.rs"

